# Generated by Django 5.0.7 on 2025-09-27 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OCUPADA', 'Ocupada'), ('DESOCUPADA', 'Desocupada'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DESOCUPADA', max_length=20, verbose_name='Estado')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('cantidad_vehiculos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Vehículos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Unidad Habitacional',
                'verbose_name_plural': 'Unidades Habitacionales',
                'ordering': ['direccion'],
                'indexes': [models.Index(fields=['estado'], name='unidades_un_estado_942014_idx'), models.Index(fields=['direccion'], name='unidades_un_direcci_c78358_idx')],
            },
        ),
    ]
