# Generated by Django 5.0.7 on 2025-09-30 04:27

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas_comunes', '0001_initial'),
        ('residentes', '0006_merge_20250929_0502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de Reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('tipo_reserva', models.CharField(choices=[('PARTICULAR', 'Uso Particular'), ('EVENTO', 'Evento'), ('REUNION', 'Reunión'), ('DEPORTE', 'Deporte'), ('OTRO', 'Otro')], default='PARTICULAR', max_length=20, verbose_name='Tipo de Reserva')),
                ('motivo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Motivo de la Reserva')),
                ('numero_personas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Personas')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('observaciones_admin', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observaciones del Administrador')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('administrador_aprobacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador que Aprobó')),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='areas_comunes.areacomun', verbose_name='Área Común')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='residentes.residente', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_reserva', 'hora_inicio'], name='reservas_re_fecha_r_350ea0_idx'), models.Index(fields=['estado'], name='reservas_re_estado_7c17e1_idx'), models.Index(fields=['area_comun', 'fecha_reserva'], name='reservas_re_area_co_857a92_idx'), models.Index(fields=['residente'], name='reservas_re_residen_339d09_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='reserva_hora_fin_mayor_inicio'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('fecha_reserva__gte', datetime.date(2025, 9, 30))), name='reserva_fecha_futura'),
        ),
    ]
