# Generated by Django 5.0.7 on 2025-09-28 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_maxima', models.IntegerField()),
                ('precio_por_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, upload_to='areas_comunes/')),
                ('activo', models.BooleanField(default=True)),
                ('requiere_pago', models.BooleanField(default=False)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='22:00')),
                ('dias_disponibles', models.JSONField(default=list, help_text='Lista de días disponibles: 0=Lunes, 6=Domingo')),
                ('tiempo_minimo_reserva', models.IntegerField(default=1, help_text='Horas mínimas de reserva')),
                ('tiempo_maximo_reserva', models.IntegerField(default=4, help_text='Horas máximas de reserva')),
                ('anticipacion_minima', models.IntegerField(default=24, help_text='Horas de anticipación mínima')),
                ('anticipacion_maxima', models.IntegerField(default=720, help_text='Horas de anticipación máxima (30 días)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bloqueo', 'Bloqueo/Mantenimiento'), ('evento', 'Evento Especial'), ('reservado', 'Reservado por Administración')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.areacomun')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad Especial',
                'verbose_name_plural': 'Disponibilidades Especiales',
            },
        ),
        migrations.CreateModel(
            name='ReglamentoReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_vigencia', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area_comun', models.ForeignKey(blank=True, help_text='Si no se especifica, aplica para todas las áreas', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.areacomun')),
            ],
            options={
                'verbose_name': 'Reglamento de Reservas',
                'verbose_name_plural': 'Reglamentos de Reservas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No se presentó')], default='pendiente', max_length=20)),
                ('numero_personas', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.areacomun')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('area_comun', 'fecha_reserva', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('descuento_cuota', 'Descuento de Cuota')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.FileField(blank=True, upload_to='comprobantes_reservas/')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('procesado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Pago de Reserva',
                'verbose_name_plural': 'Pagos de Reservas',
            },
        ),
        migrations.CreateModel(
            name='NotificacionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación de Reserva'), ('recordatorio', 'Recordatorio'), ('cancelacion', 'Cancelación'), ('cambio', 'Cambio de Estado')], max_length=20)),
                ('mensaje', models.TextField()),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('canal', models.CharField(default='email', max_length=20)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Notificación de Reserva',
                'verbose_name_plural': 'Notificaciones de Reservas',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_reservas', models.IntegerField(default=0)),
                ('reservas_confirmadas', models.IntegerField(default=0)),
                ('reservas_canceladas', models.IntegerField(default=0)),
                ('no_shows', models.IntegerField(default=0)),
                ('ingresos_generados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_ocupadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tasa_ocupacion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.areacomun')),
            ],
            options={
                'verbose_name': 'Estadística de Reservas',
                'verbose_name_plural': 'Estadísticas de Reservas',
                'unique_together': {('fecha', 'area_comun')},
            },
        ),
    ]
