# Generated by Django 5.0.7 on 2025-09-28 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_confianza_facial', models.FloatField(default=0.6, help_text='Umbral de confianza para reconocimiento facial (0.0-1.0)')),
                ('umbral_confianza_ocr', models.FloatField(default=0.8, help_text='Umbral de confianza para OCR de placas (0.0-1.0)')),
                ('activo_deteccion_anomalias', models.BooleanField(default=True)),
                ('sensibilidad_anomalias', models.IntegerField(default=5, help_text='Sensibilidad de detección (1-10, donde 10 es más sensible)')),
                ('horario_inicio', models.TimeField(default='06:00')),
                ('horario_fin', models.TimeField(default='22:00')),
                ('enviar_notificaciones_push', models.BooleanField(default=True)),
                ('email_alertas', models.EmailField(blank=True, max_length=254)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuraciones de IA',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_accesos', models.IntegerField(default=0)),
                ('accesos_residentes', models.IntegerField(default=0)),
                ('accesos_visitantes', models.IntegerField(default=0)),
                ('accesos_denegados', models.IntegerField(default=0)),
                ('alertas_generadas', models.IntegerField(default=0)),
                ('vehiculos_detectados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadística de Seguridad',
                'verbose_name_plural': 'Estadísticas de Seguridad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AlertaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('acceso_no_autorizado', 'Acceso No Autorizado'), ('persona_desconocida', 'Persona Desconocida'), ('vehiculo_no_autorizado', 'Vehículo No Autorizado'), ('comportamiento_sospechoso', 'Comportamiento Sospechoso'), ('perro_suelto', 'Perro Suelto'), ('mal_estacionamiento', 'Mal Estacionamiento'), ('zona_restringida', 'Acceso a Zona Restringida')], max_length=30)),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=10)),
                ('descripcion', models.TextField()),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='alertas/')),
                ('camara_id', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Seguridad',
                'verbose_name_plural': 'Alertas de Seguridad',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='FotoResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_residentes/')),
                ('encoding_facial', models.TextField(blank=True, help_text='Encoding facial generado por face_recognition')),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_referencia', to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Foto de Residente',
                'verbose_name_plural': 'Fotos de Residentes',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('auto', 'Automóvil'), ('moto', 'Motocicleta'), ('camioneta', 'Camioneta'), ('bicicleta', 'Bicicleta')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('ci', models.CharField(blank=True, max_length=20)),
                ('foto_entrada', models.ImageField(upload_to='visitantes/')),
                ('encoding_facial', models.TextField(blank=True)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('residente_visitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('tipo_persona', models.CharField(choices=[('residente', 'Residente'), ('visitante', 'Visitante'), ('personal', 'Personal'), ('desconocido', 'Desconocido')], max_length=20)),
                ('foto_acceso', models.ImageField(upload_to='accesos/')),
                ('confianza_reconocimiento', models.FloatField(default=0, help_text='Nivel de confianza del reconocimiento facial (0-100)')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('camara_id', models.CharField(default='cam_01', max_length=50)),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residentes.residente')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ia_seguridad.visitante')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
