# Generated by Django 5.0.7 on 2025-09-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('fija', 'Cámara Fija'), ('ptz', 'Cámara PTZ'), ('domo', 'Domo'), ('bullet', 'Bullet')], default='fija', max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'Mantenimiento'), ('error', 'Error')], default='activa', max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('puerto', models.IntegerField(default=554)),
                ('usuario', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('url_rtsp', models.URLField(blank=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('fecha_instalacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cámara',
                'verbose_name_plural': 'Cámaras',
            },
        ),
    ]
