# Generated by Django 5.0.7 on 2025-09-28 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica_multas_automaticas', models.BooleanField(default=True)),
                ('dias_gracia', models.IntegerField(default=5, help_text='Días de gracia antes de aplicar multa')),
                ('porcentaje_multa', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('monto_multa_fija', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('enviar_recordatorios', models.BooleanField(default=True)),
                ('dias_antes_vencimiento', models.IntegerField(default=7)),
                ('dias_despues_vencimiento', models.IntegerField(default=3)),
                ('descuento_pago_anticipado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dias_pago_anticipado', models.IntegerField(default=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Finanzas',
                'verbose_name_plural': 'Configuraciones de Finanzas',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cuotas_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_multas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('residentes_morosos', models.IntegerField(default=0)),
                ('porcentaje_cobro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cuotas_pagadas', models.IntegerField(default=0)),
                ('cuotas_pendientes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadística Financiera',
                'verbose_name_plural': 'Estadísticas Financieras',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TipoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_fija', models.BooleanField(default=True, help_text='Si es fija, el monto no cambia')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cuota',
                'verbose_name_plural': 'Tipos de Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=20)),
                ('mes_periodo', models.DateField(help_text='Mes al que corresponde la cuota')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.residente')),
                ('tipo_cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.tipocuota')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'unique_together': {('residente', 'tipo_cuota', 'mes_periodo')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('cheque', 'Cheque'), ('online', 'Pago en Línea')], max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, help_text='Número de transacción, cheque, etc.', max_length=100)),
                ('comprobante', models.FileField(blank=True, upload_to='comprobantes/')),
                ('observaciones', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.cuota')),
                ('procesado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='RecordatorioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recordatorio', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notificación Push'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_programada', models.DateTimeField()),
                ('mensaje_personalizado', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.cuota')),
            ],
            options={
                'verbose_name': 'Recordatorio de Pago',
                'verbose_name_plural': 'Recordatorios de Pago',
            },
        ),
        migrations.CreateModel(
            name='ReporteFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('mensual', 'Reporte Mensual'), ('anual', 'Reporte Anual'), ('morosidad', 'Reporte de Morosidad'), ('ingresos', 'Reporte de Ingresos'), ('custom', 'Reporte Personalizado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('archivo_reporte', models.FileField(upload_to='reportes_financieros/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Financiero',
                'verbose_name_plural': 'Reportes Financieros',
            },
        ),
    ]
