# Generated by Django 5.0.7 on 2025-09-29 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas_comunes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('MOBILIARIO', 'Mobiliario'), ('ELECTRODOMESTICO', 'Electrodoméstico'), ('EQUIPO_TECNOLOGICO', 'Equipo Tecnológico'), ('HERRAMIENTA', 'Herramienta'), ('DECORACION', 'Decoración'), ('OTRO', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_REPARACION', 'En reparación'), ('DADO_DE_BAJA', 'Dado de baja')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Estimado (Bs)')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('area_comun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='areas_comunes.areacomun', verbose_name='Área Común')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
