# Generated by Django 5.0.7 on 2025-09-21 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('modulo', models.CharField(choices=[('USUARIOS', 'Usuarios'), ('ADMINISTRACION', 'Administracion'), ('TRANSPORTE', 'Transporte'), ('RESERVAS', 'Reservas'), ('PAGOS', 'Pagos'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
            ],
        ),
    ]
