# Generated by Django 5.0.7 on 2025-09-21 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(default='', max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(default='', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='Email')),
                ('ci', models.CharField(default='', max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('nro_licencia', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de licencia debe contener solo letras mayúsculas y números', regex='^[A-Z0-9]+$')], verbose_name='Número de Licencia')),
                ('tipo_licencia', models.CharField(choices=[('A', 'Tipo A - Motocicletas'), ('B', 'Tipo B - Vehículos particulares'), ('C', 'Tipo C - Vehículos de carga liviana'), ('D', 'Tipo D - Vehículos de carga pesada'), ('E', 'Tipo E - Vehículos de transporte público')], max_length=1, verbose_name='Tipo de Licencia')),
                ('fecha_venc_licencia', models.DateField(verbose_name='Fecha de Vencimiento de Licencia')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('descanso', 'En Descanso'), ('inactivo', 'Inactivo')], default='disponible', max_length=20, verbose_name='Estado')),
                ('experiencia_anios', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de Emergencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('ultima_ubicacion_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Última Ubicación - Latitud')),
                ('ultima_ubicacion_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Última Ubicación - Longitud')),
                ('ultima_actualizacion_ubicacion', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización de Ubicación')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
