# Generated by Django 5.0.7 on 2025-09-21 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['nro_licencia'], name='conductores_nro_lic_cd83a4_idx'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['fecha_venc_licencia'], name='conductores_fecha_v_cf0014_idx'),
        ),
    ]
