# Generated by Django 5.0.7 on 2025-09-21 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código de empleado debe contener solo letras mayúsculas y números', regex='^[A-Z0-9]+$')], verbose_name='Código de Empleado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de Emergencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
