# Generated by Django 5.0.7 on 2025-09-21 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['ci'], name='personal_pe_ci_e50515_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['email'], name='personal_pe_email_04dc33_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['codigo_empleado'], name='personal_pe_codigo__53f11e_idx'),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_personal_email'),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(fields=('ci',), name='unique_personal_ci'),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(fields=('codigo_empleado',), name='unique_personal_codigo_empleado'),
        ),
    ]
