# Generated by Django 5.0.7 on 2025-09-29 15:23

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaComun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                (
                    "monto_hora",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "ACTIVO"),
                            ("INACTIVO", "INACTIVO"),
                            ("MANTENIMIENTO", "MANTENIMIENTO"),
                        ],
                        default="ACTIVO",
                        max_length=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Área Común",
                "verbose_name_plural": "Áreas Comunes",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["estado"], name="areas_comunes_estado_idx"),
                    models.Index(
                        django.db.models.functions.text.Lower("nombre"),
                        name="areas_comunes_nombre_ci_idx",
                    ),
                ],
            },
        ),
    ]
