# Generated by Django 5.0.7 on 2025-09-28 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal', max_length=7)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Mantenimiento',
                'verbose_name_plural': 'Categorías de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tareas_completadas', models.IntegerField(default=0)),
                ('tareas_pendientes', models.IntegerField(default=0)),
                ('incidentes_reportados', models.IntegerField(default=0)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo_total_trabajado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tareas_emergencia', models.IntegerField(default=0)),
                ('eficiencia_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Estadística de Mantenimiento',
                'verbose_name_plural': 'Estadísticas de Mantenimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('emergencia', 'Emergencia'), ('mejora', 'Mejora/Actualización')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='pendiente', max_length=20)),
                ('proveedor_externo', models.CharField(blank=True, help_text='Empresa o proveedor externo', max_length=200)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completion', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('materiales_necesarios', models.TextField(blank=True)),
                ('herramientas_necesarias', models.TextField(blank=True)),
                ('tiempo_estimado', models.DecimalField(decimal_places=2, default=0, help_text='Horas', max_digits=5)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fotos_antes', models.JSONField(blank=True, null=True)),
                ('fotos_despues', models.JSONField(blank=True, null=True)),
                ('documentos', models.JSONField(blank=True, null=True)),
                ('es_recurrente', models.BooleanField(default=False)),
                ('frecuencia_dias', models.IntegerField(blank=True, null=True)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Personal interno asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personal')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.categoriamantenimiento')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('porcentaje_completado', models.IntegerField(default=0)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('costo_parcial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fotos', models.JSONField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'verbose_name': 'Seguimiento de Tarea',
                'verbose_name_plural': 'Seguimientos de Tareas',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_uso', models.DateField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.material')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'verbose_name': 'Material Utilizado',
                'verbose_name_plural': 'Materiales Utilizados',
            },
        ),
        migrations.CreateModel(
            name='IncidenteMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('evaluando', 'En Evaluación'), ('aprobado', 'Aprobado'), ('asignado', 'Asignado'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='reportado', max_length=20)),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('contacto_reportador', models.CharField(blank=True, max_length=200)),
                ('fotos_incidente', models.JSONField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_evaluacion', models.TextField(blank=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_evaluados', to=settings.AUTH_USER_MODEL)),
                ('reportado_por_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea_generada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'verbose_name': 'Incidente de Mantenimiento',
                'verbose_name_plural': 'Incidentes de Mantenimiento',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='TareaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('tiempo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('materiales', models.TextField(blank=True)),
                ('instrucciones', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.categoriamantenimiento')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.planmantenimiento')),
            ],
            options={
                'verbose_name': 'Tarea Recurrente',
                'verbose_name_plural': 'Tareas Recurrentes',
            },
        ),
    ]
