# Generated by Django 5.0.7 on 2025-09-26 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20250925_1635'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Título o nombre de la notificación', max_length=200, verbose_name='Nombre de la Notificación')),
                ('descripcion', models.TextField(help_text='Contenido detallado de la notificación', verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('mantenimiento', 'Mantenimiento'), ('reunion', 'Reunión'), ('aviso', 'Aviso'), ('emergencia', 'Emergencia'), ('pagos', 'Pagos'), ('evento', 'Evento')], default='general', max_length=20, verbose_name='Tipo de Notificación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('es_individual', models.BooleanField(default=False, help_text='Si es True, se puede asignar a usuarios específicos', verbose_name='¿Es notificación individual?')),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Fecha y hora para enviar la notificación', null=True, verbose_name='Fecha Programada')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha hasta cuando la notificación es válida', null=True, verbose_name='Fecha de Expiración')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('requiere_confirmacion', models.BooleanField(default=False, help_text='Si requiere que el destinatario confirme la lectura', verbose_name='Requiere Confirmación')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('roles_destinatarios', models.ManyToManyField(blank=True, help_text='Roles que recibirán esta notificación', to='users.rol', verbose_name='Roles Destinatarios')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
