# Generated by Django 5.0.7 on 2025-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada'), ('leida', 'Leída')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
