# Generated by Django 5.0.7 on 2025-09-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(default='', max_length=100, verbose_name='Apellido')),
                ('ci', models.CharField(default='', max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(default='', max_length=20, verbose_name='Teléfono')),
                ('unidad_habitacional', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Número de Casa')),
                ('tipo', models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino')], max_length=20, verbose_name='Tipo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('en_proceso', 'En Proceso de Aprobación')], default='en_proceso', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residente_set', to='unidades.unidadhabitacional', verbose_name='Unidad Habitacional')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['unidad_habitacional'], name='residentes__unidad__c50d62_idx'), models.Index(fields=['fecha_ingreso'], name='residentes__fecha_i_257133_idx'), models.Index(fields=['tipo'], name='residentes__tipo_48fa6e_idx')],
            },
        ),
    ]
