# Generated by Django 5.0.7 on 2025-09-27 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residente_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='residente',
            index=models.Index(fields=['unidad_habitacional'], name='residentes__unidad__c50d62_idx'),
        ),
        migrations.AddIndex(
            model_name='residente',
            index=models.Index(fields=['fecha_ingreso'], name='residentes__fecha_i_257133_idx'),
        ),
        migrations.AddIndex(
            model_name='residente',
            index=models.Index(fields=['tipo'], name='residentes__tipo_48fa6e_idx'),
        ),
    ]
