# Generated by Django 5.0.7 on 2025-09-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_auto_update_unidad_relation'),
        ('residentes', '0002_residente_usuario'),
        ('residentes', '0003_update_unidad_habitacional_field'),
    ]

    operations = [
    ]
