# Generated by Django 5.0.7 on 2025-09-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0004_merge_20250929_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='unidad',
        ),
        migrations.AddField(
            model_name='residente',
            name='unidad_habitacional',
            field=models.CharField(blank=True, help_text='Código de la unidad (ej: A-101, B-202)', max_length=10, null=True, verbose_name='Código de Unidad Habitacional'),
        ),
    ]
