# Generated by Django 5.0.7 on 2025-09-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_initial'),
        ('residentes', '0005_remove_residente_unidad_and_more'),
    ]

    operations = [
    ]
