# Generated by Django 5.0.7 on 2025-10-02 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaseguridad',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
